---
- name: install mariadb
  apt: 
    name: 
      - mariadb-server
      - mariadb-cline
    state: present

- name: Configure MariaDB on localhost
  ini_file:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    section: mysqld
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: 'innodb_file_per_table', value: '1' }
    - { option: 'lower_case_table_names', value: '0' }
  notify: Restart mariadb

#- name: Create .my.cnf
#  template:
#   src: "client.my.cnf.j2"
#   dest: "/root/.my.cnf"
#   owner: root
#   group: root
#   mode: 0600

#- name: Set DB root Password
#  mysql_user:
#    login_unix_socket: "{{ librenms_database_socket }}"
#    login_host: 'localhost'
#    login_user: 'root'
#    #login_password: "{{ librenms_database_login_password }}"
#    name: 'root'
#    password: "{{ librenms_database_login_password }}"
#    check_implicit_admin: true
#    priv: "*.*:ALL"
#    state: present

- name: Configure MariaDB
  script: ./dbscript.sh
  

  

