---
# Configure MariaDB

# modify 50-server file
- block:
  - name: grant access from remote 
    replace: 
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Configure MariaDB on localhost
    ini_file:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      section: mysqld
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    loop:
      - { option: 'innodb_file_per_table', value: '1' }
      - { option: 'lower_case_table_names', value: '0' }
    notify: Restart mariadb

- name: Set DB root Password
  mysql_user:
    login_unix_socket: "{{ librenms_database_socket }}"
    login_host: 'localhost'
    login_user: 'root'
    #login_password: "{{ librenms_database_login_password }}"
    name: 'root'
    password: "{{ librenms_database_login_password }}"
    check_implicit_admin: true
    #priv: "*.*:ALL"
    state: present
    #host: 0.0.0.0

-name: 
