---
- name: Fail if OS is not Ubuntu 18.04
  assert:
    that:
      - "ansible_distribution == 'Ubuntu'"
      - "ansible_distribution_release == 'focal'"
    fail_msg: "This role only supports deployment to Ubuntu 20.04 systems"


- name: Change system timezone
  timezone: 
    name: "{{ librenms_timezone}}"

- name: Install software-properties-common
  apt: 
    name: software-properties-common
    state: present

- name: set universal Repositories
  shell: add-apt-repository universe

- name: Install Required Packages
  apt: 
    name: "{{librenms_packages}}"
    state: present
    update_cache: True

- name: Add user libreNMS
  user:
    name: "{{ librenms_system_user }}"
    home: "{{ librenms_install_dir }}"
    create_home: no
    system: yes

- name: Download LibreNMS
  git:
    repo: "https://github.com/librenms/librenms.git"
    dest: "{{ librenms_install_dir }}"
    # version: "{{ librenms_version }}"
    update: no # No update, because the LibreNMS cronjob does this if set.

- name: chown librenms
  file:
    path: /opt/librenms
    owner: librenms
    group: librenms
    recurse: yes

- name: set acl
  acl:
    path: "/opt/librenms/{{ item }}"
    default: yes
    recursive: yes
    etype: group
    permissions: rwx 
    state: present
  with_items:
  - rrd
  - logs
  - bootstrap/cache
  - storage

- name: Set date.timezone for CLI
  lineinfile:
    dest: "/etc/php/{{ librenms_php_version }}/{{ item }}/php.ini"
    regexp: '^;date.timezone ='
    line: date.timezone = "{{ librenms_timezone }}"
  notify: Restart PHP
  loop:
    - fpm
    - cli





