---
# should check install, new install, post-install, fix issue, etc
# e.g. reset admin password, add new user
# plugin should also be post-installation
# TODO: remote access MariaDB, poller use remote db, redis, memcache etc, remote replication
- name: Fail if OS is not Ubuntu 20
  assert:
    that:
      - "ansible_distribution == 'Ubuntu'"
      - "ansible_distribution_release == 'focal'"
    fail_msg: "This role only supports deployment to Ubuntu 20.04 systems"
- import_tasks: ConfigMariadb_ext.yml
#- import_tasks: main_0.yml
#- import_tasks: main_1.yml
#- import_tasks: validate.yml
