---
- name: Fail if OS is not Ubuntu 18.04
  assert:
    that:
      - "ansible_distribution == 'Ubuntu'"
      - "ansible_distribution_release == 'bionic'"
    fail_msg: "This role only supports deployment to Ubuntu 18.04 systems"

- name: Include LibreNMS setup tasks
  include_tasks: setup-LibreNMS.yml

- name: Include MariaDB setup tasks
  include_tasks: setup-MariaDB.yml

- name: Include web server setup tasks
  include_tasks: setup-web.yml

- name: Include LibreNMS configuration tasks
  include_tasks: configure.yml

- name: Change ownership of all LibreNMS directories
  file:
    path: "{{ librenms_install_dir }}"
    owner: "{{ librenms_system_user }}"
    group: "{{ librenms_system_user }}"
    recurse: yes

- name: Set ACL on required LibreNMS sub-directories
  acl:
    path: "{{ item }}"
    etype: group
    permissions: rwx
    default: yes
    recursive: yes
    state: present
  loop:
    - "{{ librenms_install_dir }}/rrd"
    - "{{ librenms_install_dir }}/logs"
    - "{{ librenms_install_dir }}/bootstrap/cache"
    - "{{ librenms_install_dir }}/storage/"

- name: Change permissions on certain LibreNMS sub-directories
  file:
    path: "{{ item }}"
    mode: "u=rwX,g=rwX"
    recursive: yes
  loop:
    - "{{ librenms_install_dir }}/rrd"
    - "{{ librenms_install_dir }}/logs"
    - "{{ librenms_install_dir }}/bootstrap/cache"
    - "{{ librenms_install_dir }}/storage/"
