---
- name: Install prerequisite packages
  apt:
    name: "{{ librenms_packages }}"
    cache_valid_time: 3600

- name: Add LibreNMS user
  user:
    name: "{{ librenms_system_user }}"
    home: "{{ librenms_install_dir }}"
    create_home: no
    system: yes

- name: Clone LibreNMS repository
  git:
    repo: "https://github.com/librenms/librenms.git"
    dest: "{{ librenms_install_dir }}"
    version: "{{ librenms_version }}"
    update: no # No update, because the LibreNMS cronjob does this if set.

- name: Install PHP dependencies
  composer:
    command: install
    working_dir: "{{ librenms_install_dir }}"
