---
- name: Install MariaDB server package
  apt:
    name: mariadb-server
  when: "librenms_database_login_host == 'localhost'"

- name: Create database via local socket
  mysql_db:
    name: "{{ librenms_database_name }}"
    login_host: "{{ librenms_database_login_host }}"
    login_port: "{{ librenms_database_login_port }}"
    login_user: "{{ librenms_database_login_user }}"
    login_password: "{{ librenms_database_login_password }}"
    encoding: utf8
    collation: utf8_unicode_ci
  notify: Restart mysql

- name: Create database user
  mysql_user:
    name: "{{ librenms_database_user }}"
    host: "{{ librenms_database_host }}"
    password: "{{ librenms_database_password }}"
    login_host: "{{ librenms_database_login_host }}"
    login_port: "{{ librenms_database_login_port }}"
    login_user: "{{ librenms_database_login_user }}"
    login_password: "{{ librenms_database_login_password }}"
    priv: '{{ librenms_database_name }}.*:ALL'
  notify: Restart mysql

- name: Configure MariaDB
  ini_file:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    section: mysqld
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: 'innodb_file_per_table', value: '1' }
    - { option: 'lower_case_table_names', value: '0' }
  notify: Restart mysql
