---
- name: Install prerequisite packages
  apt:
    name: "{{ librenms_packages }}"

- name: Add LibreNMS user
  user:
    name: "{{ librenms_user }}"
    home: "{{ librenms_install_dir }}"
    create_home: no
    system: yes
    groups: www-data

- name: Clone LibreNMS repository
  git:
    repo: "https://github.com/librenms/librenms.git"
    dest: "{{ librenms_install_dir }}"
    version: "{{ librenms_version }}"

- name: Install PHP dependencies
  composer:
    command: install
    working_dir: "{{ librenms_install_dir }}"
