---
- name: Install prerequisite packages
  apt:
    name: "{{ librenms_packages }}"

- name: Add LibreNMS user
  user:
    name: librenms
    home: "{{ librenms_install_dir }}"
    create_home: no
    system: yes
    groups: www-data

- name: Clone LibreNMS repository
  git:
    repo: "https://github.com/librenms/librenms.git"
    dest: "{{ librenms_install_dir }}"
    version: "{{ librenms_version }}"
    update: "{{ librenms_update }}"

- name: Change ownership of LibreNMS directory
  file:
    path: "{{ librenms_install_dir }}"
    owner: librenms
    group: librenms
    mode: '0770'
    recurse: yes

- name: Set ACL on required LibreNMS sub-directories
  acl:
    path: "{{ item }}"
    etype: group
    permissions: rwx
    default: yes
    recursive: yes
    state: present
  loop:
    - "{{ librenms_install_dir }}/rrd"
    - "{{ librenms_install_dir }}/logs"
    - "{{ librenms_install_dir }}/bootstrap/cache"
    - "{{ librenms_install_dir }}/storage/"

- name: Install PHP dependencies
  composer:
    command: install
    working_dir: "{{ librenms_install_dir }}"
